# Auto-generated Pydantic models

from pydantic import BaseModel

# generated by datamodel-codegen:
#   filename:  app.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Aws(BaseModel, frozen=True):
    account_name: str = ""


class Source(BaseModel, frozen=True):
    project_name: str = ""
    git_origin_url: str = ""
    production_branch_name: str = ""
    aws: Aws


class Aws1(BaseModel, frozen=True):
    account_name: str = ""
    db_arn: str = ""


class Db(BaseModel, frozen=True):
    name: str = ""
    server_name: str = ""
    host: str = ""
    aws: Aws1


class Confluence(BaseModel, frozen=True):
    group_web_url: str = ""


class Box(BaseModel, frozen=True):
    group_web_url: str = ""


class Jira(BaseModel, frozen=True):
    project_keys: List[str] = ""
    group_web_url: str = ""


class ServiceNow(BaseModel, frozen=True):
    group_web_url: str = ""
    assignment_group_names: List[str] = ""


class Datadog(BaseModel, frozen=True):
    group_web_url: str = ""


class Aws2(BaseModel, frozen=True):
    account_name: str = ""


class Environment(BaseModel, frozen=True):
    env: str = ""
    name: str = ""
    host: str = ""
    app_profile: str = ""
    deploy_profile: str = ""
    deploy_pipeline_name: str = ""
    git_branch: str = ""
    aws: Aws2


class AppModel(BaseModel, frozen=True):
    name: str = ""
    short_name: str = ""
    long_name: str = ""
    description: str = ""
    org: str = ""
    group: str = ""
    app_profile: str = ""
    deploy_profile: str = ""
    source: Source
    dbs: List[Db]
    confluence: Confluence
    box: Box
    jira: Jira
    service_now: ServiceNow
    datadog: Datadog
    environments: List[Environment]


# generated by datamodel-codegen:
#   filename:  app_profiles.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class AppProfile(BaseModel, frozen=True):
    name: str = ""
    description: str = ""
    type: str = ""


class AppProfilesModel(BaseModel, frozen=True):
    app_profiles: List[AppProfile]


# generated by datamodel-codegen:
#   filename:  app_topo.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Source(BaseModel, frozen=True):
    git_branch_name: str = ""
    git_origin_url: str = ""
    project_name: str = ""


class Codepipeline(BaseModel, frozen=True):
    name: str = ""
    arn: str = ""


class Ecs(BaseModel, frozen=True):
    cluster_name: str = ""
    service_name: str = ""
    task_definition_arn: str = ""


class Alb(BaseModel, frozen=True):
    arn: str = ""
    name: str = ""
    dns_name: str = ""


class Db(BaseModel, frozen=True):
    name: str = ""
    arn: str = ""
    identifier: str = ""


class Rds(BaseModel, frozen=True):
    dbs: List[Db]


class Bucket(BaseModel, frozen=True):
    name: str = ""
    arn: str = ""


class S3(BaseModel, frozen=True):
    buckets: List[Bucket]


class Aws(BaseModel, frozen=True):
    account_name: str = ""
    account_id: str = ""
    region: str = ""
    codepipeline: Codepipeline
    ecs: Ecs
    alb: Alb
    rds: Rds
    s3: S3


class AppTopoModel(BaseModel, frozen=True):
    app_name: str = ""
    env: str = ""
    deploy_profile: str = ""
    created: str = ""
    source: Source
    aws: Aws


