# generated by datamodel-codegen:
#   filename:  combined_app.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Source(BaseModel):
    git_branch_name: str
    git_origin_url: str
    project_name: str


class Codepipeline(BaseModel):
    name: str
    arn: str


class Ecs(BaseModel):
    cluster_name: str
    service_name: str
    task_definition_arn: str


class Alb(BaseModel):
    arn: str
    name: str
    dns_name: str


class Db(BaseModel):
    name: str
    arn: str
    identifier: str


class Rds(BaseModel):
    dbs: List[Db]


class Bucket(Codepipeline):
    pass


class S3(BaseModel):
    buckets: List[Bucket]


class Aws(BaseModel):
    account_name: str
    account_id: str
    region: str
    codepipeline: Codepipeline
    ecs: Ecs
    alb: Alb
    rds: Rds
    s3: S3


class AppTopo(BaseModel):
    app_name: str
    env: str
    deploy_profile: str
    created: str
    source: Source
    aws: Aws


class Properties(BaseModel):
    app_topo: AppTopo


class Model(BaseModel):
    title: str
    type: str
    properties: Properties
    required: List[str]
