# generated by datamodel-codegen:
#   filename:  combined_group.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Member(BaseModel):
    name: str
    work_email: str
    title: str
    web_url: str


class AwsAccount(BaseModel):
    name: str
    account_id: str
    region: str
    description: str


class Confluence(BaseModel):
    name: str
    description: str
    url: str


class Box(Confluence):
    pass


class Jira(Confluence):
    pass


class DataDog(Confluence):
    pass


class AssignmentGroup(BaseModel):
    name: str
    apps: List


class ServiceNow(BaseModel):
    name: str
    description: str
    url: str
    assignment_groups: List[AssignmentGroup]


class Group(BaseModel):
    name: str
    full_name: str
    description: str
    members: List[Member]
    aws_accounts: List[AwsAccount]
    confluence: Confluence
    box: Box
    jira: Jira
    data_dog: DataDog
    service_now: ServiceNow


class Properties(BaseModel):
    group: Group


class Model(BaseModel):
    title: str
    type: str
    properties: Properties
    required: List[str]
