# Auto-generated Pydantic models

from pydantic import BaseModel

# generated by datamodel-codegen:
#   filename:  group.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Member(BaseModel, frozen=True):
    name: str = ""
    work_email: str = ""
    title: str = ""
    web_url: str = ""


class AwsAccount(BaseModel, frozen=True):
    name: str = ""
    account_id: str = ""
    region: str = ""
    description: str = ""


class Confluence(BaseModel, frozen=True):
    name: str = ""
    description: str = ""
    url: str = ""


class Box(BaseModel, frozen=True):
    name: str = ""
    description: str = ""
    url: str = ""


class Jira(BaseModel, frozen=True):
    name: str = ""
    description: str = ""
    url: str = ""


class DataDog(BaseModel, frozen=True):
    name: str = ""
    description: str = ""
    url: str = ""


class AssignmentGroup(BaseModel, frozen=True):
    name: str = ""
    apps: List


class ServiceNow(BaseModel, frozen=True):
    name: str = ""
    description: str = ""
    url: str = ""
    assignment_groups: List[AssignmentGroup]


class GroupModel(BaseModel, frozen=True):
    name: str = ""
    full_name: str = ""
    description: str = ""
    members: List[Member]
    aws_accounts: List[AwsAccount]
    confluence: Confluence
    box: Box
    jira: Jira
    data_dog: DataDog
    service_now: ServiceNow


