# Auto-generated Pydantic models

from pydantic import BaseModel

# generated by datamodel-codegen:
#   filename:  aws_account.json

from __future__ import annotations

from pydantic import BaseModel


class AwsAccountModel(BaseModel, frozen=True):
    name: str = ""
    account_id: str = ""
    region: str = ""
    description: str = ""


# generated by datamodel-codegen:
#   filename:  deploy_profiles.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class DeployProfile(BaseModel, frozen=True):
    name: str = ""
    description: str = ""


class DeployProfilesModel(BaseModel, frozen=True):
    deploy_profiles: List[DeployProfile]


# generated by datamodel-codegen:
#   filename:  member.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class MemberModel(BaseModel, frozen=True):
    name: str = ""
    work_email: str = ""
    title: str = ""
    web_url: str = ""
    role: str = ""
    teams: List


