# Auto-generated Pydantic models

from pydantic import BaseModel

# generated by datamodel-codegen:
#   filename:  org.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class AwsAccount(BaseModel, frozen=True):
    name: str = ""
    account_id: str = ""
    region: str = ""
    description: str = ""


class Confluence(BaseModel, frozen=True):
    name: str = ""
    description: str = ""
    url: str = ""


class Box(BaseModel, frozen=True):
    name: str = ""
    description: str = ""
    url: str = ""


class Jira(BaseModel, frozen=True):
    name: str = ""
    description: str = ""
    url: str = ""


class DataDog(BaseModel, frozen=True):
    name: str = ""
    description: str = ""
    url: str = ""


class ServiceNow(BaseModel, frozen=True):
    name: str = ""
    description: str = ""
    url: str = ""


class OrgModel(BaseModel, frozen=True):
    name: str = ""
    full_name: str = ""
    description: str = ""
    aws_accounts: List[AwsAccount]
    confluence: Confluence
    box: Box
    jira: Jira
    data_dog: DataDog
    service_now: ServiceNow


