# generated by datamodel-codegen:
#   filename:  combined_org.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class AwsAccount(BaseModel):
    name: str
    account_id: str
    region: str
    description: str


class Confluence(BaseModel):
    name: str
    description: str
    url: str


class Box(Confluence):
    pass


class Jira(Confluence):
    pass


class DataDog(Confluence):
    pass


class ServiceNow(Confluence):
    pass


class Org(BaseModel):
    name: str
    full_name: str
    description: str
    aws_accounts: List[AwsAccount]
    confluence: Confluence
    box: Box
    jira: Jira
    data_dog: DataDog
    service_now: ServiceNow


class Properties(BaseModel):
    org: Org


class Model(BaseModel):
    title: str
    type: str
    properties: Properties
    required: List[str]
