# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-16T20:08:58+00:00

from __future__ import annotations
from typing import List
from pydantic import BaseModel, Extra
from web_entity import WebEntity
from app_profile import AppProfile
from deploy_profile import DeployProfile


class AwsAccountRef(BaseModel):
    account_name: str


class Source(BaseModel):
    project_name: str
    git_origin_url: str
    production_branch_name: str
    aws: AwsAccountRef


class AwsDbRef(AwsAccountRef):
    db_arn: str


class Db(NamedEntity):
    server_name: str
    host: str
    aws: AwsDbRef


class Confluence(WebEntity):
    group_web_url: str


class Box(WebEntity):
    group_web_url: str


class Jira(WebEntity):
    project_keys: List[str]
    group_web_url: str


class ServiceNow(WebEntity):
    group_web_url: str
    assignment_group_names: List[str]


class Datadog(WebEntity):
    group_web_url: str


class Environment(NamedEntity):
    env: str
    host: str
    app_profile: str
    deploy_profile: str
    deploy_pipeline_name: str
    git_branch_name: str
    aws: AwsAccountRef


class App(NamedEntity):
    class Config:
        extra = Extra.allow

    short_name: str
    long_name: str
    description: str
    org: str
    group: str
    app_profile: AppProfile
    deploy_profile: DeployProfile
    source: Source
    dbs: List[Db]
    confluence: Confluence
    box: Box
    jira: Jira
    service_now: ServiceNow
    datadog: Datadog
    environments: List[Environment]
