# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-02T06:46:05+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra


class Aws(BaseModel):
  account_name: str


class Source(BaseModel):
  project_name: str
  git_origin_url: str
  production_branch_name: str
  aws: Aws


class Aws1(BaseModel):
  account_name: str
  db_arn: str


class Db(BaseModel):
  name: str
  server_name: str
  host: str
  aws: Aws1


class Confluence(BaseModel):
  group_web_url: str


class Box(Confluence):
  pass


class Jira(BaseModel):
  project_keys: List[str]
  group_web_url: str


class ServiceNow(BaseModel):
  group_web_url: str
  assignment_group_names: List[str]


class Datadog(Confluence):
  pass


class Aws2(Aws):
  pass


class Environment(BaseModel):
  env: str
  name: str
  host: str
  app_profile: str
  deploy_profile: str
  deploy_pipeline_name: str
  git_branch_name: str
  aws: Aws2


class AppModel(BaseModel):
  class Config:
    extra = Extra.forbid

  name: str
  short_name: str
  long_name: str
  description: str
  org: str
  group: str
  app_profile: str
  deploy_profile: str
  source: Source
  dbs: List[Db]
  confluence: Confluence
  box: Box
  jira: Jira
  service_now: ServiceNow
  datadog: Datadog
  environments: List[Environment]