# generated by datamodel-codegen:
#   filename:  temp_app_topo.schema.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra, Field


class Source(BaseModel):
    class Config:
        extra = Extra.allow

    git_branch_name: str
    git_origin_url: str
    project_name: str


class Codepipeline(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    arn: str


class Ecs(BaseModel):
    class Config:
        extra = Extra.allow

    cluster_name: str
    service_name: str
    task_definition_arn: str


class Alb(BaseModel):
    class Config:
        extra = Extra.allow

    arn: str
    name: str
    dns_name: str


class Db(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    arn: str
    identifier: str


class Rds(BaseModel):
    class Config:
        extra = Extra.allow

    dbs: List[Db] = Field(..., min_items=1)


class Bucket(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    arn: str


class S3(BaseModel):
    class Config:
        extra = Extra.allow

    buckets: List[Bucket] = Field(..., min_items=1)


class Aws(BaseModel):
    class Config:
        extra = Extra.allow

    account_name: str
    account_id: str
    region: str
    codepipeline: Codepipeline
    ecs: Ecs
    alb: Alb
    rds: Rds
    s3: S3


class AppTopoModel(BaseModel):
    class Config:
        extra = Extra.allow

    app_name: str
    env: str
    deploy_profile: str
    created: str
    source: Source
    aws: Aws
