# generated by datamodel-codegen:
#   filename:  temp_app_profiles.schema.json

from __future__ import annotations

from typing import List

from pydantic import Extra

from base_model import NamedEntity


class AppProfile(NamedEntity):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    type: str


class AppProfilesModel(NamedEntity):
    class Config:
        extra = Extra.allow

    app_profiles: List[AppProfile]
