# generated by datamodel-codegen:
#   filename:  temp_app_profiles.schema.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra, Field


class AppProfile(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    type: str


class AppProfilesModel(BaseModel):
    class Config:
        extra = Extra.allow

    app_profiles: List[AppProfile] = Field(..., min_items=1)
