# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-09T00:27:30+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Aws(BaseModel):
    account_name: str


class Source(BaseModel):
    project_name: str
    git_origin_url: str
    production_branch_name: Optional[str]
    aws: Optional[Aws]
    git_branch_name: Optional[str]


class Aws1(BaseModel):
    account_name: str
    db_arn: str


class Db(BaseModel):
    name: str
    server_name: str
    host: str
    aws: Aws1


class Confluence(BaseModel):
    group_web_url: Optional[str]
    name: Optional[str]
    description: Optional[str]
    url: Optional[str]


class Box(Confluence):
    pass


class Jira(BaseModel):
    project_keys: Optional[List[str]]
    group_web_url: Optional[str]
    name: Optional[str]
    description: Optional[str]
    url: Optional[str]


class AssignmentGroup(BaseModel):
    name: str
    apps: List[str]


class ServiceNow(BaseModel):
    group_web_url: Optional[str]
    assignment_group_names: Optional[List[str]]
    name: Optional[str]
    description: Optional[str]
    url: Optional[str]
    assignment_groups: Optional[List[AssignmentGroup]]


class Datadog(Confluence):
    pass


class Aws2(Aws):
    pass


class Environment(BaseModel):
    env: str
    name: str
    host: str
    app_profile: str
    deploy_profile: str
    deploy_pipeline_name: str
    git_branch_name: str
    aws: Aws2


class AppProfile(BaseModel):
    name: str
    description: str
    type: str


class Codepipeline(BaseModel):
    name: str
    arn: str


class Ecs(BaseModel):
    cluster_name: str
    service_name: str
    task_definition_arn: str


class Alb(BaseModel):
    arn: str
    name: str
    dns_name: str


class Db1(BaseModel):
    name: str
    arn: str
    identifier: str


class Rds(BaseModel):
    dbs: List[Db1]


class Bucket(Codepipeline):
    pass


class S3(BaseModel):
    buckets: List[Bucket]


class Account(BaseModel):
    account_name: str
    account_id: str
    region: str
    description: str


class Aws3(BaseModel):
    account_name: Optional[str]
    account_id: Optional[str]
    region: Optional[str]
    codepipeline: Optional[Codepipeline]
    ecs: Optional[Ecs]
    alb: Optional[Alb]
    rds: Optional[Rds]
    s3: Optional[S3]
    accounts: Optional[List[Account]]


class DeployProfile(BaseModel):
    name: str
    description: str


class Member(BaseModel):
    name: str
    work_email: str
    title: str
    web_url: str


class AppModel(BaseModel):
    name: Optional[str]
    short_name: Optional[str]
    long_name: Optional[str]
    description: Optional[str]
    org: Optional[str]
    group: Optional[str]
    app_profile: Optional[str]
    deploy_profile: Optional[str]
    source: Optional[Source]
    dbs: Optional[List[Db]]
    confluence: Optional[Confluence]
    box: Optional[Box]
    jira: Optional[Jira]
    service_now: Optional[ServiceNow]
    datadog: Optional[Datadog]
    environments: Optional[List[Environment]]
    field_static: Optional[bool] = Field(None, alias="_static")
    app_profiles: Optional[List[AppProfile]]
    app_name: Optional[str]
    env: Optional[str]
    created: Optional[str]
    aws: Optional[Aws3]
    account_name: Optional[str]
    account_id: Optional[str]
    region: Optional[str]
    deploy_profiles: Optional[List[DeployProfile]]
    full_name: Optional[str]
    members: Optional[List[Member]]
    work_email: Optional[str]
    title: Optional[str]
    web_url: Optional[str]
    work_phone: Optional[str]
    slack_handle: Optional[str]
