# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-10T04:24:36+00:00

from __future__ import annotations

from typing import List

from base_models import NamedEntity
from pydantic import Extra


class Source(NamedEntity):
    git_branch_name: str
    git_origin_url: str
    project_name: str


class Codepipeline(NamedEntity):
    name: str
    arn: str


class Ecs(NamedEntity):
    cluster_name: str
    service_name: str
    task_definition_arn: str


class Alb(NamedEntity):
    arn: str
    name: str
    dns_name: str


class Db(NamedEntity):
    name: str
    arn: str
    identifier: str


class Rds(NamedEntity):
    dbs: List[Db]


class Bucket(Codepipeline):
    pass


class S3(NamedEntity):
    buckets: List[Bucket]


class Aws(NamedEntity):
    account_name: str
    account_id: str
    region: str
    codepipeline: Codepipeline
    ecs: Ecs
    alb: Alb
    rds: Rds
    s3: S3


class AppTopoModel(NamedEntity):
    class Config:
        extra = Extra.forbid

    app_name: str
    env: str
    deploy_profile: str
    created: str
    source: Source
    aws: Aws
