# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-15T06:24:42+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra, Field


class AppProfile(BaseModel):
    name: str
    description: str
    type: str


class AppProfiles(BaseModel):
    class Config:
        extra = Extra.allow

    field_static: bool = Field(..., alias="_static")
    app_profiles: List[AppProfile]
