# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-03T21:56:59+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra, Field


class AppProfile(BaseModel):
    name: str
    description: str
    type: str


class AppProfilesModel(BaseModel):
    class Config:
        extra = Extra.forbid

    field_static: bool = Field(..., alias="_static")
    app_profiles: List[AppProfile]
