# generated by datamodel-codegen:
#   filename:  combined_app.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class AppTopo(BaseModel):
    __root__: Any


class CombinedSchema(BaseModel):
    app_topo: AppTopo
