# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-10T04:24:36+00:00

from __future__ import annotations

from typing import List

from base_models import WebEntity
from pydantic import Extra


class Aws(WebEntity):
    account_name: str


class Source(WebEntity):
    project_name: str
    git_origin_url: str
    production_branch_name: str
    aws: Aws


class Aws1(WebEntity):
    account_name: str
    db_arn: str


class Db(WebEntity):
    name: str
    server_name: str
    host: str
    aws: Aws1


class Confluence(WebEntity):
    group_web_url: str
    space_keys: List[str]


class Box(WebEntity):
    group_web_url: str


class Jira(WebEntity):
    project_keys: List[str]
    group_web_url: str


class ServiceNow(WebEntity):
    group_web_url: str
    assignment_group_names: List[str]


class Datadog(Box):
    pass


class Aws2(Aws):
    pass


class Environment(WebEntity):
    env: str
    name: str
    host: str
    app_profile: str
    deploy_profile: str
    deploy_pipeline_name: str
    git_branch_name: str
    aws: Aws2


class AppCsgModel(WebEntity):
    class Config:
        extra = Extra.forbid

    name: str
    short_name: str
    long_name: str
    description: str
    org: str
    group: str
    app_profile: str
    deploy_profile: str
    source: Source
    dbs: List[Db]
    confluence: Confluence
    box: Box
    jira: Jira
    service_now: ServiceNow
    datadog: Datadog
    environments: List[Environment]
