# generated by datamodel-codegen:
#   filename:  temp_app.schema.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra, Field


class Aws(BaseModel):
    class Config:
        extra = Extra.allow

    account_name: str


class Source(BaseModel):
    class Config:
        extra = Extra.allow

    project_name: str
    git_origin_url: str
    production_branch_name: str
    aws: Aws


class Aws1(BaseModel):
    class Config:
        extra = Extra.allow

    account_name: str
    db_arn: str


class Db(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    server_name: str
    host: str
    aws: Aws1


class Confluence(BaseModel):
    class Config:
        extra = Extra.allow

    group_web_url: str


class Box(BaseModel):
    class Config:
        extra = Extra.allow

    group_web_url: str


class Jira(BaseModel):
    class Config:
        extra = Extra.allow

    project_keys: List[str] = Field(..., min_items=1)
    group_web_url: str


class ServiceNow(BaseModel):
    class Config:
        extra = Extra.allow

    group_web_url: str
    assignment_group_names: List[str] = Field(..., min_items=1)


class Datadog(BaseModel):
    class Config:
        extra = Extra.allow

    group_web_url: str


class Aws2(BaseModel):
    class Config:
        extra = Extra.allow

    account_name: str


class Environment(BaseModel):
    class Config:
        extra = Extra.allow

    env: str
    name: str
    host: str
    app_profile: str
    deploy_profile: str
    deploy_pipeline_name: str
    git_branch: str
    aws: Aws2


class AppModel(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    short_name: str
    long_name: str
    description: str
    org: str
    group: str
    app_profile: str
    deploy_profile: str
    source: Source
    dbs: List[Db] = Field(..., min_items=1)
    confluence: Confluence
    box: Box
    jira: Jira
    service_now: ServiceNow
    datadog: Datadog
    environments: List[Environment] = Field(..., min_items=1)
