# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-08T22:33:25+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra


class Source(BaseModel):
    git_branch_name: str
    git_origin_url: str
    project_name: str


class Codepipeline(BaseModel):
    name: str
    arn: str


class Ecs(BaseModel):
    cluster_name: str
    service_name: str
    task_definition_arn: str


class Alb(BaseModel):
    arn: str
    name: str
    dns_name: str


class Db(BaseModel):
    name: str
    arn: str
    identifier: str


class Rds(BaseModel):
    dbs: List[Db]


class Bucket(Codepipeline):
    pass


class S3(BaseModel):
    buckets: List[Bucket]


class Aws(BaseModel):
    account_name: str
    account_id: str
    region: str
    codepipeline: Codepipeline
    ecs: Ecs
    alb: Alb
    rds: Rds
    s3: S3


class AppTopoModel(BaseModel):
    class Config:
        extra = Extra.forbid

    app_name: str
    env: str
    deploy_profile: str
    created: str
    source: Source
    aws: Aws
