# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-16T20:08:58+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra, Field

from named_entity import NamedEntity

class AppProfile(NamedEntity):
    description: str
    type: str


