# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-15T06:24:42+00:00

from __future__ import annotations

from backend.app.models.web_entity import WebEntity
from pydantic import Extra


class AwsAccount(WebEntity):
    class Config:
        extra = Extra.allow

    account_name: str
    region: str
    account_id: str
