# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-02T18:57:01+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra


class AwsAccountModel(BaseModel):
    class Config:
        extra = Extra.forbid

    account_name: str
    account_id: str
    region: str
    description: str
