# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-15T06:24:42+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra, Field


class AwsAccountRef(BaseModel):
    class Config:
        extra = Extra.allow

    aws_account_name: str = Field(..., alias="aws.account_name")
