# generated by datamodel-codegen:
#   filename:  temp_aws_account.schema.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class AwsAccountModel(BaseModel):
    class Config:
        extra = Extra.allow

    account_name: str
    account_id: str
    region: str
    description: str
