# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-10T04:24:36+00:00

from __future__ import annotations

from base_models import NamedEntity
from pydantic import Extra, Field


class NamedEntityModel(NamedEntity):
    name: str


class WebEntityNamedEntity(NamedEntity):
    url: str
    description: str


class AwsAccountWebEntity(NamedEntity):
    account_name: str
    region: str
    account_id: str


class AwsAccountRef(NamedEntity):
    aws_account_name: str = Field(..., alias="aws.account_name")


class BaseModel(NamedEntity):
    class Config:
        extra = Extra.forbid

    named_entity: NamedEntityModel
    web_entity_named_entity_: WebEntityNamedEntity = Field(
        ..., alias="web_entity[named_entity]"
    )
    aws_account_web_entity_: AwsAccountWebEntity = Field(
        ..., alias="aws_account[web_entity]"
    )
    aws_account_ref: AwsAccountRef
