# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-15T06:24:42+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra, Field


class NamedEntity(BaseModel):
    name: str


class WebEntityNamedEntity(BaseModel):
    url: str
    description: str


class AwsAccountWebEntity(BaseModel):
    account_name: str
    region: str
    account_id: str


class AwsAccountRef(BaseModel):
    aws_account_name: str = Field(..., alias="aws.account_name")


class Base(BaseModel):
    class Config:
        extra = Extra.allow

    named_entity: NamedEntity
    web_entity_named_entity_: WebEntityNamedEntity = Field(
        ..., alias="web_entity[named_entity]"
    )
    aws_account_web_entity_: AwsAccountWebEntity = Field(
        ..., alias="aws_account[web_entity]"
    )
    aws_account_ref: AwsAccountRef
