# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-03T20:31:11+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra


class DeployProfile(BaseModel):
    name: str
    description: str


class DeployProfilesModel(BaseModel):
    class Config:
        extra = Extra.forbid

    deploy_profiles: List[DeployProfile]
