# generated by datamodel-codegen:
#   filename:  temp_deploy_profiles.schema.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra, Field


class DeployProfile(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: str


class DeployProfilesModel(BaseModel):
    class Config:
        extra = Extra.allow

    deploy_profiles: List[DeployProfile] = Field(..., min_items=1)
