# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-10T04:24:36+00:00

from __future__ import annotations

from typing import List

from base_models import NamedEntity
from pydantic import Extra, Field


class DeployProfile(NamedEntity):
    name: str
    description: str


class DeployProfilesModel(NamedEntity):
    class Config:
        extra = Extra.forbid

    field_static: bool = Field(..., alias="_static")
    deploy_profiles: List[DeployProfile]
