# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-16T20:08:59+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra, Field

from named_entity import NamedEntity

class DeployProfile(NamedEntity):
    description: str
