# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-16T20:08:59+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra

from web_entity import WebEntity

class Member(NamedEntity):
    work_email: str
    title: str
    web_url: str


class AwsAccount(BaseModel):
    account_name: str
    account_id: str
    region: str
    description: str


class Aws(BaseModel):
    accounts: List[AwsAccount]


class Confluence(WebEntity):
    pass

class Box(WebEntity):
    pass


class Jira(WebEntity):
    pass


class Datadog(WebEntity):
    pass


class AssignmentGroup(NamedEntity):
    apps: List[str]


class ServiceNow(WebEntity):
    assignment_groups: List[AssignmentGroup]


class Group(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    full_name: str
    description: str
    members: List[Member]
    aws: Aws
    confluence: Confluence
    box: Box
    jira: Jira
    datadog: Datadog
    service_now: ServiceNow
