# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-10T04:24:37+00:00

from __future__ import annotations

from typing import List

from base_models import WebEntity
from pydantic import Extra


class Member(WebEntity):
    name: str
    work_email: str
    title: str
    web_url: str
    role: str
    teams: List[str]


class Account(WebEntity):
    account_name: str
    account_id: str
    region: str
    description: str


class Aws(WebEntity):
    accounts: List[Account]


class Confluence(WebEntity):
    name: str
    description: str
    url: str


class Box(Confluence):
    pass


class Jira(Confluence):
    pass


class Datadog(Confluence):
    pass


class AssignmentGroup(WebEntity):
    name: str
    apps: List[str]


class ServiceNow(WebEntity):
    name: str
    description: str
    url: str
    assignment_groups: List[AssignmentGroup]


class GroupFinappsModel(WebEntity):
    class Config:
        extra = Extra.forbid

    name: str
    full_name: str
    description: str
    members: List[Member]
    aws: Aws
    confluence: Confluence
    box: Box
    jira: Jira
    datadog: Datadog
    service_now: ServiceNow
