# generated by datamodel-codegen:
#   filename:  combined_group.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class Group(BaseModel):
    __root__: Any = Field(..., description="")


class CombinedSchema(BaseModel):
    group: Group
