# generated by datamodel-codegen:
#   filename:  temp_group.schema.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra, Field


class Member(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    work_email: str
    title: str
    web_url: str


class AwsAccount(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    account_id: str
    region: str
    description: str


class Confluence(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    url: str


class Box(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    url: str


class Jira(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    url: str


class DataDog(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    url: str


class AssignmentGroup(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    apps: List[str] = Field(..., min_items=1)


class ServiceNow(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    url: str
    assignment_groups: List[AssignmentGroup] = Field(..., min_items=1)


class GroupModel(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    full_name: str
    description: str
    members: List[Member] = Field(..., min_items=1)
    aws_accounts: List[AwsAccount] = Field(..., min_items=1)
    confluence: Confluence
    box: Box
    jira: Jira
    data_dog: DataDog
    service_now: ServiceNow
