# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-15T06:24:42+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra


class Member(BaseModel):
    name: str
    work_email: str
    title: str
    web_url: str


class Account(BaseModel):
    account_name: str
    account_id: str
    region: str
    description: str


class Aws(BaseModel):
    accounts: List[Account]


class Confluence(BaseModel):
    name: str
    description: str
    url: str


class Box(Confluence):
    pass


class Jira(Confluence):
    pass


class Datadog(Confluence):
    pass


class AssignmentGroup(BaseModel):
    name: str
    apps: List[str]


class ServiceNow(BaseModel):
    name: str
    description: str
    url: str
    assignment_groups: List[AssignmentGroup]


class Group(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    full_name: str
    description: str
    members: List[Member]
    aws: Aws
    confluence: Confluence
    box: Box
    jira: Jira
    datadog: Datadog
    service_now: ServiceNow
