# generated by datamodel-codegen:
#   filename:  temp_group.schema.json

from __future__ import annotations

from typing import List

from pydantic import Extra

from base_model import NamedEntity


class Member(NamedEntity):
    class Config:
        extra = Extra.allow

    name: str
    work_email: str
    title: str
    web_url: str


class AwsAccount(NamedEntity):
    class Config:
        extra = Extra.allow

    name: str
    account_id: str
    region: str
    description: str


class Confluence(NamedEntity):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    url: str


class Box(NamedEntity):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    url: str


class Jira(NamedEntity):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    url: str


class DataDog(NamedEntity):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    url: str


class AssignmentGroup(NamedEntity):
    class Config:
        extra = Extra.allow

    name: str
    apps: List[str]


class ServiceNow(NamedEntity):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    url: str
    assignment_groups: List[AssignmentGroup]


class NamedEntityModel(NamedEntity):
    class Config:
        extra = Extra.allow

    name: str


class NameDesc(NamedEntityModel):
    class Config:
        extra = Extra.allow

    description: str
    name: str


class GroupModel(NameDesc):
    class Config:
        extra = Extra.allow

    full_name: str
    members: List[Member]
    aws_accounts: List[AwsAccount]
    confluence: Confluence
    box: Box
    jira: Jira
    data_dog: DataDog
    service_now: ServiceNow
