# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-02T18:57:02+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra


class MemberModel(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    work_email: str
    title: str
    web_url: str
