# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-15T06:24:42+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra


class Member(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    work_email: str
    title: str
    web_url: str
    work_phone: str
    slack_handle: str
