# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-08T22:33:25+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra


class MemberModel(BaseModel):
    class Config:
        extra = Extra.forbid

    name: str
    work_email: str
    title: str
    web_url: str
    work_phone: str
    slack_handle: str
