# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-10T04:24:36+00:00

from __future__ import annotations

from base_models import NamedEntity
from pydantic import Extra


class MemberModel(NamedEntity):
    class Config:
        extra = Extra.forbid

    name: str
    work_email: str
    title: str
    web_url: str
    work_phone: str
    slack_handle: str
