# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-16T20:08:58+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra


class NamedEntity(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
