# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-15T06:24:42+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra


class Account(BaseModel):
    account_name: str
    account_id: str
    region: str
    description: str


class Aws(BaseModel):
    accounts: List[Account]


class Confluence(BaseModel):
    name: str
    description: str
    url: str


class Box(Confluence):
    pass


class Jira(Confluence):
    pass


class Datadog(Confluence):
    pass


class ServiceNow(Confluence):
    pass


class Org(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    full_name: str
    description: str
    aws: Aws
    confluence: Confluence
    box: Box
    jira: Jira
    datadog: Datadog
    service_now: ServiceNow
