# generated by datamodel-codegen:
#   filename:  combined_org.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class Org(BaseModel):
    __root__: Any = Field(..., description="")


class CombinedSchema(BaseModel):
    org: Org
