# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-10T04:24:36+00:00

from __future__ import annotations

from typing import List

from base_models import WebEntity
from pydantic import Extra


class Account(WebEntity):
    account_name: str
    account_id: str
    region: str
    description: str


class Aws(WebEntity):
    accounts: List[Account]


class Confluence(WebEntity):
    name: str
    description: str
    url: str


class Box(Confluence):
    pass


class Jira(Confluence):
    pass


class Datadog(Confluence):
    pass


class ServiceNow(Confluence):
    pass


class OrgModel(WebEntity):
    class Config:
        extra = Extra.forbid

    name: str
    full_name: str
    description: str
    aws: Aws
    confluence: Confluence
    box: Box
    jira: Jira
    datadog: Datadog
    service_now: ServiceNow
