# generated by datamodel-codegen:
#   filename:  temp_org.schema.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra


class AwsAccount(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    account_id: str
    region: str
    description: str


class Confluence(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    url: str


class Box(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    url: str


class Jira(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    url: str


class DataDog(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    url: str


class ServiceNow(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    description: str
    url: str


class OrgModel(BaseModel):
    class Config:
        extra = Extra.allow

    name: str
    full_name: str
    description: str
    aws_accounts: List[AwsAccount]
    confluence: Confluence
    box: Box
    jira: Jira
    data_dog: DataDog
    service_now: ServiceNow
