# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-16T20:08:58+00:00

from __future__ import annotations

from named_entity import NamedEntity
from pydantic import Extra


class WebEntity(NamedEntity):
    class Config:
        extra = Extra.allow

    url: str
    description: str
