# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-07-15T06:24:42+00:00

from __future__ import annotations

from backend.app.models.named_entity import NamedEntity
from pydantic import Extra


class WebEntity(NamedEntity):
    class Config:
        extra = Extra.allow

    url: str
    description: str
